<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>

	<ItemGroup>
		<Compile Include="Controllers\HomeController.fs" />

		<Compile Include="Models\ApiSettings.fs" />
		<Compile Include="Models\AddPurchaseViewModel.fs" />
		<Compile Include="Models\AddPaymentViewModel.fs" />
		<Compile Include="Models\CardFinancialSummaryViewModel.fs" />
		<Compile Include="Models\CardStatementViewModel.fs" />
		<Compile Include="Models\MonthlyPurchaseTotalsViewModel.fs" />
		<Compile Include="Models\TransactionViewModel.fs" />
		<Compile Include="Models\CardDashboardViewModel.fs" />

		<Compile Include="Services\ICardApiService.fs" />
		<Compile Include="Services\CardApiService.fs" />

		<Compile Include="Controllers\CardController.fs" />

		<Compile Include="Program.fs" />
	</ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="6.0.36" />
  </ItemGroup>

</Project>
